name: Test My Action

on: [workflow_dispatch]

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Use my custom action
        uses: emecusxyz/nov@v1
        with:
          name: Emeka
